## 1. What are Tensors?
**Answer:**  
Tensors are **multi-dimensional containers for numerical data**. They generalize scalars, vectors, matrices, and higher-dimensional structures. In deep learning, everything (inputs, weights, outputs, gradients) is represented as a tensor.

**Key properties:**
- **Rank** = number of dimensions
- **Shape** = size along each dimension
- **Data type** = float32, int64, etc.

---

## 2. 0D Tensor / Scalar
**Answer:**  
A **scalar** is a single number with **zero dimensions** (rank = 0). It has no axes.

**Properties:**
- Shape: `()`
- Rank: 0
- Contains exactly 1 element

In [4]:
# Example of 0 dimension tensor
import numpy as np

a=np.array(5)
print(a)
a.ndim

5


0

## 3. 1D Tensor / Vector

A vector is a 1D array of numbers (rank = 1). It has one axis.

Properties:
- Shape: (n,)
- where n = number of elements

- Rank: 1

- Axis 0 = index of elements

In [5]:
vector= np.array([1,2,3,4])
print(vector)

[1 2 3 4]


In [6]:
vector.ndim


1

## 4. 2D Tensor / Matrix
Answer:
A matrix is a 2D grid with rows and columns (rank = 2).

Properties:

*   Shape: (rows, cols)

*   Rank: 2

*   Axis 0 = rows, Axis 1 = columns

In [8]:
matrix=np.array([[1,2,3],[3,2,4],[5,2,7]])
print(matrix)
print(matrix.shape)
matrix.ndim

[[1 2 3]
 [3 2 4]
 [5 2 7]]
(3, 3)


2

## 5. ND Tensors

---

### 📖 What are ND Tensors?

**ND Tensors** (N-Dimensional Tensors) are tensors with **3 or more dimensions** (rank ≥ 3). They extend the concept of matrices (2D) into higher-dimensional spaces.

**Key point:** Any tensor with rank ≥ 3 is called an ND tensor.

---

### Rank Breakdown

| Rank | Name | Shape Example | Description |
|------|------|---------------|-------------|
| 0 | Scalar | `()` | Single number |
| 1 | Vector | `(n,)` | 1D list |
| 2 | Matrix | `(r,c)` | 2D grid |
| **3** | **3D Tensor** | `(d,r,c)` | **Cube / stack of matrices** |
| **4** | **4D Tensor** | `(b,c,h,w)` | **Batch of images** |
| **5** | **5D Tensor** | `(b,t,c,h,w)` | **Batch of videos** |
| **6+** | **Higher** | Various | Complex scientific data |



## 6. Rank, Axes and Shape

---

### Introduction

**Rank, Axes, and Shape** are the three most important properties of any tensor. Understanding them is crucial for:
- Debugging tensor shape mismatches
- Reshaping data for neural networks
- Understanding data flow in deep learning models

---

### Comparison :

| Property | Definition | How to Check | Example |
|----------|------------|--------------|---------|
| **Rank** | Number of dimensions | `tensor.ndim` | 3 |
| **Axes** | Each specific dimension | Implicit (axis 0, 1, 2...) | Axis 0, 1, 2 |
| **Shape** | Size of each axis (tuple) | `tensor.shape` | `(3, 4, 5)` |

---

###Rank (Number of Dimensions)

**Definition:**  
Rank = **how many dimensions** a tensor has. It's also called the **degree** or **order** of the tensor.

**Simple rule:** Count the number of brackets `[ ]` you need to write it.

#### Rank Examples:
| Tensor | How to Write | Rank | Name |
|--------|--------------|------|------|
| `[5]` | `5` | 0 | Scalar |
| `[1, 2, 3]` | `[1, 2, 3]` | 1 | Vector |
| `[[1,2], [3,4]]` | One outer bracket, two inner | 2 | Matrix |
| `[[[1,2], [3,4]]]` | Three brackets | 3 | 3D Tensor |
| `[[[[1,2], [3,4]]]]` | Four brackets | 4 | 4D Tensor |


##Axes (Dimensions)
Definition:
Each dimension of a tensor is called an axis. Axes are numbered starting from 0.

Rules:

Axis 0 = outermost/first dimension

Axis 1 = second dimension

Axis 2 = third dimension

...and so on

In [9]:
# 2D Tensor: Shape (3, 4)
import torch
tensor2d = torch.tensor([[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12]])

print("2D Tensor:")
print(f"Shape: {tensor2d.shape}")  # (3, 4)
print(f"Rank: {tensor2d.ndim}")    # 2
print(f"Axis 0 size: {tensor2d.shape[0]}")  # 3 (rows)
print(f"Axis 1 size: {tensor2d.shape[1]}")  # 4 (columns)
print()

# Access elements along axes
print("Element at axis 0=0, axis 1=2:", tensor2d[0, 2])  # 3
print("Element at axis 0=2, axis 1=0:", tensor2d[2, 0])  # 9

2D Tensor:
Shape: torch.Size([3, 4])
Rank: 2
Axis 0 size: 3
Axis 1 size: 4

Element at axis 0=0, axis 1=2: tensor(3)
Element at axis 0=2, axis 1=0: tensor(9)


## Shape
Definition:
Shape = size of each axis as a tuple. It tells you exactly how many elements are along each dimension.

Syntax: (dim1, dim2, dim3, ...)

Understanding Shape:

In [10]:
# Shape examples
shape1 = ()          # Empty tuple → Scalar (0D)
shape2 = (5,)        # 1D vector with 5 elements
shape3 = (3, 4)      # 2D matrix: 3 rows, 4 columns
shape4 = (2, 3, 4)   # 3D tensor: 2 layers, 3 rows, 4 columns
shape5 = (32, 3, 224, 224)  # 4D: 32 images, 3 channels, 224x224

# Shape tells you:
# - Total elements = product of all dimensions
# - How to index the tensor
# - How to reshape the tensor

## 7. Example of 1D Tensors

---

### 📖 What is a 1D Tensor?

A **1D Tensor** (also called a **Vector**) is a one-dimensional array of numbers. It has:
- **Rank:** 1
- **Shape:** `(n,)` where n is the number of elements
- **Axis:** Only one axis (axis 0)

Real-World Examples of 1D Tensors

| Example | Description | Shape |
|---------|-------------|-------|
| **Temperature readings** | Daily temperatures for a week | `(7,)` |
| **Pixel row** | One row of pixels from an image | `(28,)` |
| **Word embedding** | Vector representation of a word | `(300,)` |
| **Audio sample** | Amplitude values over time | `(44100,)` |
| **Feature vector** | Features of a data point | `(10,)` |
| **Stock prices** | Daily closing prices | `(30,)` |

## 8. Example of 2D Tensors

---

### 📖 What is a 2D Tensor?

A **2D Tensor** (also called a **Matrix**) is a two-dimensional grid of numbers with:
- **Rank:** 2
- **Shape:** `(rows, columns)`
- **Axes:** Axis 0 = rows, Axis 1 = columns

###Real-World Examples

| Example | Description | Shape |
|---------|-------------|-------|
| **Student scores** | Students × Subjects | `(5, 3)` |
| **Grayscale image** | Height × Width | `(28, 28)` |
| **Correlation matrix** | Features × Features | `(10, 10)` |
| **Distance matrix** | Cities × Cities | `(4, 4)` |
| **RGB pixel values** | Height × Width (single channel) | `(224, 224)` |

## 9. Example of 3D Tensors

---

### 📖 What is a 3D Tensor?

A **3D Tensor** is a three-dimensional array of numbers with:
- **Rank:** 3
- **Shape:** `(depth, rows, columns)` or `(height, width, channels)`
- **Axes:** Axis 0, Axis 1, Axis 2

Think of it as a **stack of matrices** or a **cube of numbers**.

---

### Real-World Examples

| Example | Description | Shape |
|---------|-------------|-------|
| **RGB Image** | Height × Width × 3 channels | `(224, 224, 3)` |
| **Grayscale Video** | Frames × Height × Width | `(30, 64, 64)` |
| **Batch of Vectors** | Batch × Features | `(100, 50)` |
| **Feature Maps** | Channels × Height × Width | `(64, 32, 32)` |
| **Time-Series Data** | Sensors × Time × Features | `(10, 100, 3)` |

---


In [11]:
#### Basic 3D Tensor Creation
import torch

# 3D tensor: 2 layers, 3 rows, 4 columns
tensor3d = torch.randn(2, 3, 4)

print("3D Tensor Properties:")
print(f"Shape: {tensor3d.shape}")  # (2, 3, 4)
print(f"Rank: {tensor3d.ndim}")    # 3
print(f"Axis 0: {tensor3d.shape[0]}")  # 2 (layers)
print(f"Axis 1: {tensor3d.shape[1]}")  # 3 (rows)
print(f"Axis 2: {tensor3d.shape[2]}")  # 4 (columns)
print(f"Total elements: {tensor3d.numel()}")  # 24

3D Tensor Properties:
Shape: torch.Size([2, 3, 4])
Rank: 3
Axis 0: 2
Axis 1: 3
Axis 2: 4
Total elements: 24


## 10. Example of 4D Tensors

---

### 📖 What is a 4D Tensor?

A **4D Tensor** is a four-dimensional array of numbers with:
- **Rank:** 4
- **Shape:** `(batch, channels, height, width)` or `(batch, height, width, channels)`
- **Axes:** Axis 0, 1, 2, 3

In [13]:
# Batch of 32 RGB images (224x224)
image_batch = torch.randn(32, 3, 224, 224)

print("Batch of RGB Images:")
print(f"Shape: {image_batch.shape}")  # (32, 3, 224, 224)
print(f"Batch size: {image_batch.shape[0]}")  # 32
print(f"First image: {image_batch[0].shape}")  # (3, 224, 224)
print(f"First image, Red channel: {image_batch[0, 0].shape}")  # (224, 224)
print(f"First 5 images: {image_batch[:5].shape}")  # (5, 3, 224, 224)
print(f"Pixel (image 0, channel 1, row 10, col 20): {image_batch[0, 1, 10, 20]:.3f}")

Batch of RGB Images:
Shape: torch.Size([32, 3, 224, 224])
Batch size: 32
First image: torch.Size([3, 224, 224])
First image, Red channel: torch.Size([224, 224])
First 5 images: torch.Size([5, 3, 224, 224])
Pixel (image 0, channel 1, row 10, col 20): 0.003
